sudo: required

language: bash

services:
  - docker

script:
# Build image
  - docker build -t  algoretum/django .
# Test image
#  - docker run algoretum/django python3 --version

# Push image
  - >
    if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
    TAG=$(grep "ENV DJANGO_VER" Dockerfile | awk '{print $3}') ;
    docker tag algoretum/django algoretum/django:$TAG ;
    docker push algoretum/django:$TAG ;
    docker push algoretum/django ;
    fi

